package apperror

import "errors"

var (
	ErrNotFound   = errors.New("order not found")
	ErrValidation = errors.New("validation error")
	ErrServer     = errors.New("unexpected server error")
	// Validate order
	ErrOrderUIDMissing           = errors.New("order_uid is missing")
	ErrTrackNumberMissing        = errors.New("track number is missing")
	ErrEntryMissing              = errors.New("entry is missing")
	ErrLocaleMissing             = errors.New("locale is missing")
	ErrCustomerIDMissing         = errors.New("customer id is missing")
	ErrDeliveryServiceMissing    = errors.New("delivery service is missing")
	ErrShardkeyMissing           = errors.New("shardkey is missing")
	ErrInvalidSmID               = errors.New("invalid sm id")
	ErrDeliveryNameMissing       = errors.New("delivery name is missing")
	ErrDeliveryPhoneMissing      = errors.New("delivery phone is missing")
	ErrDeliveryZIPMissing        = errors.New("delivery ZIP is missing")
	ErrDeliveryCityMissing       = errors.New("delivery city is missing")
	ErrDeliveryAddressMissing    = errors.New("delivery address is missing")
	ErrDeliveryRegionMissing     = errors.New("delivery region is missing")
	ErrDeliveryEmailMissing      = errors.New("delivery email is missing")
	ErrPaymentTransactionMissing = errors.New("payment transaction is missing")
	ErrPaymentCurrencyMissing    = errors.New("payment currency is missing")
	ErrPaymentAmountInvalid      = errors.New("payment amount is invalid")
	ErrPaymentDeliveryInvalid    = errors.New("payment delivery cost is invalid, lower zero")
	ErrPaymentGoodsTotalInvalid  = errors.New("payment goods total is invalid")
	ErrItemsEmpty                = errors.New("items empty")
	ErrItemNameMissing           = errors.New("name is missing")
	ErrItemChrtMissing           = errors.New("chrt id is invalid")
	ErrItemPriceInvalid          = errors.New("price is invalid")
	ErrItemSaleInvalid           = errors.New("sale is invalid")
	ErrItemTotalPriceInvalid     = errors.New("total price is invalid")
	ErrStatusCodeInvalid         = errors.New("status code is invalid")
)
