// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/GameXost/wbTestCase/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepo creates a new instance of MockOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepo {
	mock := &MockOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepo is an autogenerated mock type for the OrderRepo type
type MockOrderRepo struct {
	mock.Mock
}

type MockOrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepo) EXPECT() *MockOrderRepo_Expecter {
	return &MockOrderRepo_Expecter{mock: &_m.Mock}
}

// CreateFullOrder provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) CreateFullOrder(ctx context.Context, order *models.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateFullOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepo_CreateFullOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFullOrder'
type MockOrderRepo_CreateFullOrder_Call struct {
	*mock.Call
}

// CreateFullOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *models.Order
func (_e *MockOrderRepo_Expecter) CreateFullOrder(ctx interface{}, order interface{}) *MockOrderRepo_CreateFullOrder_Call {
	return &MockOrderRepo_CreateFullOrder_Call{Call: _e.mock.On("CreateFullOrder", ctx, order)}
}

func (_c *MockOrderRepo_CreateFullOrder_Call) Run(run func(ctx context.Context, order *models.Order)) *MockOrderRepo_CreateFullOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Order
		if args[1] != nil {
			arg1 = args[1].(*models.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_CreateFullOrder_Call) Return(err error) *MockOrderRepo_CreateFullOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepo_CreateFullOrder_Call) RunAndReturn(run func(ctx context.Context, order *models.Order) error) *MockOrderRepo_CreateFullOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullOrderOnId provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) GetFullOrderOnId(ctx context.Context, OrderUId string) (*models.Order, error) {
	ret := _mock.Called(ctx, OrderUId)

	if len(ret) == 0 {
		panic("no return value specified for GetFullOrderOnId")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Order, error)); ok {
		return returnFunc(ctx, OrderUId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Order); ok {
		r0 = returnFunc(ctx, OrderUId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, OrderUId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_GetFullOrderOnId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullOrderOnId'
type MockOrderRepo_GetFullOrderOnId_Call struct {
	*mock.Call
}

// GetFullOrderOnId is a helper method to define mock.On call
//   - ctx context.Context
//   - OrderUId string
func (_e *MockOrderRepo_Expecter) GetFullOrderOnId(ctx interface{}, OrderUId interface{}) *MockOrderRepo_GetFullOrderOnId_Call {
	return &MockOrderRepo_GetFullOrderOnId_Call{Call: _e.mock.On("GetFullOrderOnId", ctx, OrderUId)}
}

func (_c *MockOrderRepo_GetFullOrderOnId_Call) Run(run func(ctx context.Context, OrderUId string)) *MockOrderRepo_GetFullOrderOnId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_GetFullOrderOnId_Call) Return(order *models.Order, err error) *MockOrderRepo_GetFullOrderOnId_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepo_GetFullOrderOnId_Call) RunAndReturn(run func(ctx context.Context, OrderUId string) (*models.Order, error)) *MockOrderRepo_GetFullOrderOnId_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentIDs provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) GetRecentIDs(ctx context.Context, amount uint64) ([]string, error) {
	ret := _mock.Called(ctx, amount)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]string, error)); ok {
		return returnFunc(ctx, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []string); ok {
		r0 = returnFunc(ctx, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_GetRecentIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentIDs'
type MockOrderRepo_GetRecentIDs_Call struct {
	*mock.Call
}

// GetRecentIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - amount uint64
func (_e *MockOrderRepo_Expecter) GetRecentIDs(ctx interface{}, amount interface{}) *MockOrderRepo_GetRecentIDs_Call {
	return &MockOrderRepo_GetRecentIDs_Call{Call: _e.mock.On("GetRecentIDs", ctx, amount)}
}

func (_c *MockOrderRepo_GetRecentIDs_Call) Run(run func(ctx context.Context, amount uint64)) *MockOrderRepo_GetRecentIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_GetRecentIDs_Call) Return(strings []string, err error) *MockOrderRepo_GetRecentIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockOrderRepo_GetRecentIDs_Call) RunAndReturn(run func(ctx context.Context, amount uint64) ([]string, error)) *MockOrderRepo_GetRecentIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderCache creates a new instance of MockOrderCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderCache {
	mock := &MockOrderCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderCache is an autogenerated mock type for the OrderCache type
type MockOrderCache struct {
	mock.Mock
}

type MockOrderCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderCache) EXPECT() *MockOrderCache_Expecter {
	return &MockOrderCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockOrderCache
func (_mock *MockOrderCache) Get(key string) (*models.Order, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Order
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*models.Order, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.Order); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockOrderCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockOrderCache_Expecter) Get(key interface{}) *MockOrderCache_Get_Call {
	return &MockOrderCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockOrderCache_Get_Call) Run(run func(key string)) *MockOrderCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderCache_Get_Call) Return(order *models.Order, b bool) *MockOrderCache_Get_Call {
	_c.Call.Return(order, b)
	return _c
}

func (_c *MockOrderCache_Get_Call) RunAndReturn(run func(key string) (*models.Order, bool)) *MockOrderCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// LoadFull provides a mock function for the type MockOrderCache
func (_mock *MockOrderCache) LoadFull(ids []*models.Order) {
	_mock.Called(ids)
	return
}

// MockOrderCache_LoadFull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadFull'
type MockOrderCache_LoadFull_Call struct {
	*mock.Call
}

// LoadFull is a helper method to define mock.On call
//   - ids []*models.Order
func (_e *MockOrderCache_Expecter) LoadFull(ids interface{}) *MockOrderCache_LoadFull_Call {
	return &MockOrderCache_LoadFull_Call{Call: _e.mock.On("LoadFull", ids)}
}

func (_c *MockOrderCache_LoadFull_Call) Run(run func(ids []*models.Order)) *MockOrderCache_LoadFull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.Order
		if args[0] != nil {
			arg0 = args[0].([]*models.Order)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderCache_LoadFull_Call) Return() *MockOrderCache_LoadFull_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderCache_LoadFull_Call) RunAndReturn(run func(ids []*models.Order)) *MockOrderCache_LoadFull_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type MockOrderCache
func (_mock *MockOrderCache) Set(order *models.Order) {
	_mock.Called(order)
	return
}

// MockOrderCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockOrderCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - order *models.Order
func (_e *MockOrderCache_Expecter) Set(order interface{}) *MockOrderCache_Set_Call {
	return &MockOrderCache_Set_Call{Call: _e.mock.On("Set", order)}
}

func (_c *MockOrderCache_Set_Call) Run(run func(order *models.Order)) *MockOrderCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Order
		if args[0] != nil {
			arg0 = args[0].(*models.Order)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderCache_Set_Call) Return() *MockOrderCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderCache_Set_Call) RunAndReturn(run func(order *models.Order)) *MockOrderCache_Set_Call {
	_c.Run(run)
	return _c
}
